### ISSUE TITLE
Keep getting errors when running install.sh

### ISSUE THREAD

**Issue by toineenzo** [carlosonunez/obs-installer-for-apple-silicon#50]
Hi,

I already tried a lot of times to make a built with the included install.sh script, but every time it stops at around 50% and gives the following error:
```
[ 53%] Building C object plugins/obs-filters/CMakeFiles/obs-filters.dir/noise-suppress-filter.c.o
[ 53%] Built target mac-decklink
[ 53%] Built target obs-transitions
[ 53%] Linking C shared module obs-filters.so
[ 53%] Built target obs-filters
make: *** [all] Error 2
[vr 25 feb 2022 20:46:15 CET] FATAL: Unable to build OBS; see above logs for more info. Try running this instead: REPACKAGE=true ./install.sh
```

and when I run `REPACKAGE=true ./install.sh` it gives me the same error.

I already tried to clean all packages, check for updates in all my package managers, install the LTS version and a newer version of node.js (if that's actually being used in the script), but that also didn't help. Does anybody know a solution?

You can find my full log here, which also contains a lot of errors: https://pastebin.com/VenXYaPq

**Comment by toineenzo** [comment]
Also, the Download Experimental Official Build-option DOES work and gives me not a single error.

**Comment by carlosonunez** [comment]
Hello! Thanks for using my script.

It looks like the build script is having trouble finding `libjansson`:

> `/tmp/obs/plugins/obs-outputs/ftl-sdk/libftl/ingest.c:5:10: fatal error: 'jansson.h' file not found`

I thought I fixed this a few releases ago; I'll see if I can repro.

**Comment by carlosonunez** [comment]
Can you try the latest build?

**Comment by lurenJBD** [comment]
<img width="1654" alt="error2" src="https://user-images.githubusercontent.com/31967654/159130607-0c32649e-8e61-430d-8cf9-789ca24e8808.png">


> Can you try the latest build?

Still get same Error

**Comment by lurenJBD** [comment]
> <img alt="error2" width="1654" src="https://user-images.githubusercontent.com/31967654/159130607-0c32649e-8e61-430d-8cf9-789ca24e8808.png">
> 
> > Can you try the latest build?
> 
> Still get same Error
> 
> Bash Raw output https://pastebin.com/uR2FErVk

I think I find a way to fix it
<img width="1680" alt="fixit" src="https://user-images.githubusercontent.com/31967654/159131922-d4540161-1b02-414c-9b22-f7d34a77694e.png">

download this two files form https://github.com/akheron/jansson/tree/master/src

and then put them to 

> /tmp/obs/plugins/obs-outputs/ftl-sdk/libftl/

then rename **jansson_config.h.in** to  **jansson_config.h**

run the script again , Hope it would help you.
